[settings.ruby]
compile = false

[tools]
ruby = 'latest'

[tasks.install]
run = """
cd $MISE_PROJECT_ROOT && \
gem install bundler && \
bundle install
"""

[tasks.preview]
description = 'Show final adoc file after includes, before compilation'
usage = '''
arg "<file>" help="File to open" default="src/index.adoc"
'''
run = """
cd $MISE_PROJECT_ROOT && \
asciidoctor-reducer \
  -a root=$(pwd) \
  -a assets_root=/assets \
  -r ./asciidoc/extensions/converter.rb \
  -r ./asciidoc/extensions/custom_macros.rb \
  -r ./asciidoc/extensions/generate_index.rb \
  $usage_file
"""

[tasks.build]
description = 'Compile all adoc files'
run = """
cd $MISE_PROJECT_ROOT && \
asciidoctor \
  --verbose \
  -a root=$(pwd) \
  -a assets_root=/assets \
  -R src \
  -r ./asciidoc/extensions/converter.rb \
  -r ./asciidoc/extensions/custom_macros.rb \
  -r ./asciidoc/extensions/generate_index.rb \
  -D _site 'src/**/*.adoc'
"""

[tasks.open]
description = 'Open a given page'
wait_for = ['build']
usage = '''
flag "-O --opener <command>" help="Page-opening command" {
  choices "open" "termux-open" "xdg-open"
  default "open"
}
flag "-b --browser <browser_name>" help="Browser (or other app) to open the page with" default="Firefox"
flag "-F --file <file_name>" help="File to open" default="_site/index.html"
'''
run = """
cd $MISE_PROJECT_ROOT && \
$usage_opener \
  -a $usage_browser \
  $usage_file
"""
