name: Deploy

on:
  push:
    branches:
      - main
      - adoc

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use mise
        uses: jdx/mise-action@v2.0.2

      - name: Build AsciiDoc files
        run: |
          mkdir -p _site
          mise r build
          cp -r css _site/ 2>/dev/null || true
          cp favicon.ico _site/ 2>/dev/null || true
          mkdir -p _site/assets/svg
          cp -r asciidoc/assets/svg _site/assets/ 2>/dev/null || true
          mkdir -p _site/assets/js
          cp -r asciidoc/assets/js _site/assets/ 2>/dev/null || true

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
